### ISSUE TITLE
Capes shift up when wearing chestplate.

### ISSUE THREAD

**Issue by goopgab** [SFort/MC-skinshine#1]
![2020-11-03_08 50 50](https://user-images.githubusercontent.com/73893219/97993561-3a093c00-1db2-11eb-9cca-afb492e22637.png)
1.16.3 fabric

**Comment by SFort** [comment]
sorry, i  have no idea where this happens

**Comment by SFort** [comment]
Awfully late fix but it is fixed in  [1.1.6](https://github.com/SFort/MC-skinshine/releases/download/r1.1.6/skinshine-1.1.6.jar)
thanks for the bug report
