### ISSUE TITLE
[Suggestion] Ability to display armor translucent

### ISSUE THREAD

**Issue by RubixDev** [SFort/MC-skinshine#2]
I would like to have the ability to make the armor appear translucent not fully invisible, so one can still see what armor the other wears, while also being able to see the skin.

**Comment by SFort** [comment]
# Gotta love minecraft transperency!
This is a sodium conflict.
(just as a heads up that if you get this i'm not fixing it)
![screenshot](https://user-images.githubusercontent.com/1879846/124278993-7a35df80-db36-11eb-8fd2-45e90891a7ad.png)
