### ISSUE TITLE
Compatibility Request: Wildfire's Gender Mod

### ISSUE THREAD

**Issue by AzureMonument** [SFort/MC-skinshine#3]
![image](https://user-images.githubusercontent.com/43318292/125828282-d3984ee2-1ea0-436d-b8e8-ff4ab1430e80.png)

As you can see, the chestplate does not completely disappear with Wildfire's Gender mod. It'd be nice if it did, but I'm not sure if that is something that can be done on this side. 

Thanks for the mod~

**Comment by SFort** [comment]
Wierd mod you found there it's simulteniously licanced as "CC0 (no rights reserved)"and "all rights reverved". WP dev i have no idea what i'm allowed todo licance wise

Glad you like the mod i'll take a look at it.

**Comment by SFort** [comment]
Can't do a thing, has to be added in the gender mod.
